// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/kujtimiihoxha/kit/test_dir/math/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	SumEndpoint  endpoint.Endpoint
	ProdEndpoint endpoint.Endpoint
	SubEndpoint  endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.MathService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{
		ProdEndpoint: MakeProdEndpoint(s),
		SubEndpoint:  MakeSubEndpoint(s),
		SumEndpoint:  MakeSumEndpoint(s),
	}
	for _, m := range mdw["Sum"] {
		eps.SumEndpoint = m(eps.SumEndpoint)
	}
	for _, m := range mdw["Prod"] {
		eps.ProdEndpoint = m(eps.ProdEndpoint)
	}
	for _, m := range mdw["Sub"] {
		eps.SubEndpoint = m(eps.SubEndpoint)
	}
	return eps
}
