// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package endpoint

import (
	endpoint "github.com/go-kit/kit/endpoint"
	service "github.com/kujtimiihoxha/kit/test_dir/strings/pkg/service"
)

// Endpoints collects all of the endpoints that compose a profile service. It's
// meant to be used as a helper struct, to collect all of the endpoints into a
// single parameter.
type Endpoints struct {
	TaskEndpoint endpoint.Endpoint
}

// New returns a Endpoints struct that wraps the provided service, and wires in all of the
// expected endpoint middlewares
func New(s service.StringsService, mdw map[string][]endpoint.Middleware) Endpoints {
	eps := Endpoints{TaskEndpoint: MakeTaskEndpoint(s)}
	for _, m := range mdw["Task"] {
		eps.TaskEndpoint = m(eps.TaskEndpoint)
	}
	return eps
}
