// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	grpc "github.com/go-kit/kit/transport/grpc"
	endpoint "github.com/kujtimiihoxha/kit/test_dir/math/pkg/endpoint"
	pb "github.com/kujtimiihoxha/kit/test_dir/math/pkg/grpc/pb"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	sum  grpc.Handler
	prod grpc.Handler
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.MathServer {
	return &grpcServer{
		prod: makeProdHandler(endpoints, options["Prod"]),
		sum:  makeSumHandler(endpoints, options["Sum"]),
	}
}
